# Generated by Django 5.0.6 on 2024-05-31 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='user',
            new_name='referrer',
        ),
    ]
