# Generated by Django 5.0.6 on 2024-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0007_waitinguser_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_link',
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
