# Generated by Django 5.0.6 on 2024-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='faquestion',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
